// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import config from './src/config/config';

export default defineConfig({
  schema: 'src/infrastructure/database/prisma/schemas/schema.prisma',
  migrations: {
    path: 'src/infrastructure/database/migrations',
    seed: 'tsx src/infrastructure/database/seeders/index.ts',
  },
  // engine: 'classic',
  datasource: {
    url: config.database.url,
  },
});
